name: MAIN
on:
  pull_request:
    types: [opened, reopened]
#  schedule:
#    - cron: '*/5 13/15 2/3 12 *'
  workflow_dispatch:
env:
  RUN_A: true
  RUN_B: false
jobs:
  echo:
    name: Odpala tylko gdy RUN_B
    if: ${{ env.RUN_B }}
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Cześć co u Ciebie?"
      - name: check node version
        run: node --version
      - name: check npm version
        run: npm --version
  echo2:
    name: Odpala tylko gdy RUN_A
    if: ${{ env.RUN_A }}
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Cześć co u Ciebie?"
      - name: check node version
        run: node --version
      - name: check npm version
        run: npm --version
