name: MAIN
on:
  pull_request:
    branches:
      - '!main'
#  schedule:
#    - cron: '*/5 13/15 2/3 12 *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cześć co u Ciebie?"
