name: MAIN
on:
  pull_request:
#  schedule:
#    - cron: '*/5 13/15 2/3 12 *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo Dodano lub usunieto git branch albo tag ($GITHUB_SHA / $GITHUB_REF)
