name: MAIN
on:
  create:
  delete:
  schedule:
    - cron: '*/5 13/15 2/3 12 *'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo Dodano lub usunieto git branch albo tag ($GITHUB_SHA / $GITHUB_REF)
