name: MAIN
on:
  push:
    branches:
      - 'main'
#  schedule:
#    - cron: '*/5 13/15 2/3 12 *'
  workflow_dispatch:
env:
  RUN_A: true
  RUN_B: false
jobs:
  echo:
    name: Odpala tylko gdy RUN_B
    #if: ${{ env.RUN_B }}
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        id: output-source
        run: |
          echo "Cześć co u Ciebie?"
          echo "IMIE=Tomasz" >> "$GITHUB_OUTPUT"
      - name: check node version
        env:
          IMIE: ${{steps.output-source.outputs.IMIE}}
        run: |
          node --version
          echo "A spoko. A u Ciebie $IMIE?"
      - name: check npm version
        run: npm --version
  echo2:
    name: Odpala tylko gdy RUN_A
    #if: ${{ env.RUN_A }}
    runs-on: ubuntu-latest
    steps:
      - name: debugnijmy
        run: echo "::error file=appka.js,line=12::Set the Octocat variable"
      - name: dodajmy env variabla
        run: echo "RUN_C=true" >> "$GITHUB_ENV"
      - name: i od razu go odczytajmy
        run: echo $RUN_C
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: I odpalenie skryptu
        env:
          SIEMANO: no cześć
        run: ./skrypt.sh
        shell: bash
