name: Inny job per folder w którym jest zmiana
on:
  push:
    branches: [ "main" ]
env:
  ZMIANY: ${{ toJSON(github.event) }}
jobs:
  in_folder1:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Takie tam 1
        run: echo Coś zmieniło się w folderze 1 $ZMIANY
  in_folder2:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Takie tam 2
        run: echo Coś zmieniło się w folderze 2 $ZMIANY
