name: Inny job per folder w którym jest zmiana
on:
  push:
    branches: [ "main" ]
jobs:
  changes_checker:
    runs-on: ubuntu-latest
    outputs:
        changesInFolder1: ${{ steps.check_changes.outputs.changesInFolder1 }}
        changesInFolder2: ${{ steps.check_changes.outputs.changesInFolder2 }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sprawdz czy w folderze 1 i 2 były zmiany
        run: |
          echo Previous commit SHA ${{ github.event.before }}
          echo Current commit SHA ${{ github.sha }}
          echo After commit SHA ${{ github.event.after }}

          FOLDER_CHANGES_1=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- 'folder1/*')
          if [ -n "$FOLDER_CHANGES_1" ]; then
            echo "Changes were made in the folder 1 $FOLDER_CHANGES_1"
            echo "changesInFolder1=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes were made in the folder"
            echo "changesInFolder1=false" >> "$GITHUB_OUTPUT"
          fi
          FOLDER_CHANGES_2=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- 'folder2/*')
          if [ -n "$FOLDER_CHANGES_2" ]; then
            echo "Changes were made in the folder 2 $FOLDER_CHANGES_2"
            echo "changesInFolder2=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes were made in the folder"
            echo "changesInFolder2=false" >> "$GITHUB_OUTPUT"
          fi
        id: check_changes
  in_folder1:
    needs: changes_checker
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.changes_checker.outputs.changesInFolder1) }}
    steps:
      - name: Takie tam 1
        run: echo Coś zmieniło się w folderze 1
  in_folder2:
    needs: changes_checker
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.changes_checker.outputs.changesInFolder2) }}
    steps:
      - name: Takie tam 2
        run: echo Coś zmieniło się w folderze 2
