name: Cyklicznie
on:
  schedule:
  - cron: '9 * * * *'
jobs:
  simple_echo:
    runs-on: ubuntu-latest
    steps:
      - name: Just echo
        run: echo Odpalam w 5 minucie każdej godziny i każdego dnia
